Retry upload, download, and delete after a slow-down response
wasabi-tech/s3-benchmark pull request #5
Opened 2018-07-26 22:29 UTC by lrobwebster

2018-07-27 13:25 UTC, jcflowers commented on s3-benchmark.go
> +			if (resp.StatusCode == http.StatusServiceUnavailable) {
Why not just count the error and try again?  The slow down will automatically delay you.

2018-07-27 13:26 UTC, jcflowers requested changes

2018-07-27 13:26 UTC, jcflowers commented on s3-benchmark.go
> -				body, _ := ioutil.ReadAll(resp.Body)
Why not just count the error and try again? The slow down will automatically delay you.

2018-08-08 13:33 UTC, jcflowers approved these changes

2018-08-08 14:54 UTC, merged

2019-04-26 20:11 UTC, razorsedge commented
Looks like #2 was partially added in this PR as well.